### ISSUE TITLE
Decidir melhor modelo de landing page

### ISSUE THREAD

**Issue by capaolab** [capaolab/capaolab.github.io#1]
**Descrição**

Precisamos decidir o melhor modelo de langing page para o projeto.  Inicialmente precisamos de uma pagina de apresentação da ONG e uma pagina para apresentar os bootcaps . 

**Critério de Aceite**

 Precisamos criar um documento na wiki do projeto com definições básicas para a landing page: cores, seções, componentes e etc.

**Comment by dean-almeida** [comment]
@viriatonova  [Wiki modelo da landing page](https://github.com/capaolab/capaolab.github.io/wiki/Modelo-landing-page)

**Comment by viriatonova** [comment]
Tá bom. A demo tá bem no stilo que precisamos
